football:
  outputs:
    dev:
      dataset: football_silver
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: football-pipeline-498403
      threads: 4
      type: bigquery
  target: dev
